services:
  postgres:
    image: postgres:15-alpine
    container_name: sri_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: sri_api_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sri_network

  redis:
    image: redis:7-alpine
    container_name: sri_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - sri_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sri_api
    # Sobrescribimos el comando por defecto para que corra en modo desarrollo y escuche cambios
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      # Dentro de Docker, nos conectamos usando los nombres de los servicios DNS de Docker
      - DATABASE_URL=postgresql://postgres:SecretPassword123!@postgres:5432/sri_api_db
      - REDIS_URL=redis://redis:6379
      - ENCRYPTION_KEY=MiSuperClaveSecretaAES25612345!
      - MOCK_SRI=true
    volumes:
      - .:/app                 # Monta el código local dentro del contenedor para Hot-Reload
      - /app/node_modules      # Evita que el node_modules local sobrescriba al del contenedor
    depends_on:
      - postgres
      - redis
    networks:
      - sri_network

volumes:
  pgdata:
  redisdata:

networks:
  sri_network:
    driver: bridge
