export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TENANT_ALREADY_EXISTS = 'TENANT_ALREADY_EXISTS',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  TENANT_CERTIFICATE_NOT_FOUND = 'TENANT_CERTIFICATE_NOT_FOUND',
  SIGNING_ERROR = 'SIGNING_ERROR',
}
